version: '3.6'
services:

  app:
    build: docker/nginx
    ports:
      - 443:443
    links:
      - phpfpm
    volumes:
      - ./src/knowBase:/var/www/html
      - ./share-files/composer:/var/www/.composer
      - ./share-files/logs/nginx:/var/log/nginx
    networks:
      - wp-network

  phpfpm:
    build: docker/phpfpm
    links:
      - db
    environment:
      XDEBUG_CONFIG: idekey=PHPSTORM
    volumes:
      - ./src/knowBase:/var/www/html
      - ./share-files/composer:/var/www/html/var/composer_home
      - ./share-files/composer:/var/www/.composer
    networks:
      - wp-network

#  db:
#    build: ./docker/mysql
#    ports:
#      - "3306:3306"
#    volumes:
#      - ./share-files/backup:/tmp/db
#      - ./share-files/database:/var/lib/mysql
#    env_file: docker/mysql/config/mysql.env
#    networks:
#      - wp-network

  db:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wp-network
    restart: on-failure
    ports:
      - "3306:3306"
    volumes:
      - ./share-files/backup:/tmp/db
      - ./share-files/database:/var/lib/mysql
    env_file: docker/mysql/config/mysql.env

volumes:
  sockdata:

networks:
  wp-network:
    driver: bridge